version: '2'

services:

    niamoto-rabbitmq:
        build: ./niamoto-rabbitmq
        restart: always

    niamoto-nginx:
        build: ./niamoto-nginx
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
            - "5555:5555"
        depends_on:
            - niamoto-django
        volumes_from:
            - niamoto-django:ro
        extra_hosts:
            - "niamoto-geoserver:54.190.55.248"
        restart: always

    niamoto-django:
        build:
            context: ./niamoto-django
        depends_on:
            - niamoto-rabbitmq
        volumes:
            - niamoto-django_site_media:/home/niamoto/niamoto-portal/site_media
            - /home/niamoto/NIAMOTO_BACKUPS:/home/niamoto/niamoto-portal/data/backups

        restart: always

volumes:

    niamoto-django_site_media:
        external: false

