version: '2'

services:

    niamoto-geoserver:
        build: ./niamoto-geoserver
        volumes:
            - niamoto-geoserver_data:/opt/geoserver/data_dir
        restart: always

    niamoto-rabbitmq:
        build: ./niamoto-rabbitmq
        restart: always

    niamoto-nginx:
        build: ./niamoto-nginx
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
            - "5555:5555"
        depends_on:
            - niamoto-django
            - niamoto-geoserver
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
            - /etc/ssl/certs:/etc/ssl/certs
        volumes_from:
            - niamoto-django:ro
            - niamoto-geoserver:ro
        restart: always

    niamoto-django:
        build:
            context: ./niamoto-django
        depends_on:
            - niamoto-geoserver
            - niamoto-rabbitmq
        volumes:
            - niamoto-django_site_media:/home/niamoto/niamoto-portal/site_media
            - /home/niamoto/NIAMOTO_BACKUPS:/home/niamoto/niamoto-portal/data/backups
        extra_hosts:
            - "niamoto-postgres:172.31.25.118"

        restart: always

volumes:
    niamoto-geoserver_data:
        external: false

    niamoto-django_site_media:
        external: false

